export const districtMap: Record<string, string> = {
  Colombo: 'LK-11',
  Gampaha: 'LK-12',
  Kalutara: 'LK-13',
  Mahanuwara: 'LK-21',
  Matale: 'LK-22',
  Nuwaraeliya: 'LK-23',
  Galle: 'LK-31',
  Matara: 'LK-32',
  Hambantota: 'LK-33',
  Jaffna: 'LK-41',
  Vanni: 'LK-43',
  Batticaloa: 'LK-51',
  Digamadulla: 'LK-52',
  Trincomalee: 'LK-53',
  Kurunegala: 'LK-61',
  Puttalam: 'LK-62',
  Anuradhapura: 'LK-71',
  Polonnaruwa: 'LK-72',
  Badulla: 'LK-81',
  Ratnapura: 'LK-91',
  Monaragala: 'LK-82',
  Kegalle: 'LK-92',
};
